# -*- coding: utf-8 -*-
"""airline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yfsIgj8g22rMbKs9qap02uTHsTOD-QC

DAY-1

TASK:Load Dataset Airline and generate first five rows and last five rows
"""

# Import required libraries

import numpy as np

import pandas as pd

print("Numpy imported successfully")

print("Pandas imported successfully")

import os
os.getcwd()

#Loading Dataset
df_airline = pd.read_csv("/content/airlines_flights_data.csv")

print("Dataset loaded successfully")

#Display first rows
df_airline.head(5)

#Display last 5 rows

df_airline.tail(5)

"""DAY 2

Task - Load Dataset Airline and apply all the pandas operations
"""

#Loading Dataset

df_airline = pd.read_csv("/content/airlines_flights_data.csv")

print("Dataset loaded successfully")

#code1

df_airline.head()

#code2

df_airline.tail()

#code3

df_airline.shape

#code7

df_airline.describe()

#code8

df_airline ["airline"]

#code6

df_airline.info()